(function(){'use strict';
  const board=document.querySelector('#board'),status=document.querySelector('#status'),reset=document.querySelector('#reset');let state;
  function message(){return state.phase==='finished'?'정렬 완료 · 다음 견본을 시작할 수 있습니다.':'옆의 활자를 눌러 빈칸으로 옮기세요.';}
  function render(focusIndex){board.innerHTML='';state.board.forEach((value,index)=>{const movable=Fifteen.isLegalMove(state,index),row=Math.floor(index/4)+1,col=index%4+1;const cell=document.createElement('button');cell.type='button';cell.className=value?'tile':'tile blank';cell.dataset.index=index;cell.disabled=!value||state.phase==='finished'||!movable;cell.setAttribute('aria-label',value?`${row}행 ${col}열, ${value}번 활자${movable?', 빈칸으로 이동 가능':''}`:`${row}행 ${col}열, 빈칸`);if(value)cell.textContent=value;board.append(cell);});status.textContent=message();board.classList.toggle('complete',state.phase==='finished');if(Number.isInteger(focusIndex))board.querySelector(`[data-index="${focusIndex}"]`)?.focus();}
  function move(index){if(!Fifteen.isLegalMove(state,index))return;const moved=state.board[index];state=Fifteen.play(state,index);const next=state.board.findIndex((_,cell)=>Fifteen.isLegalMove(state,cell));render(next);status.textContent=state.phase==='finished'?message():`${moved}번 활자를 빈칸으로 옮겼습니다.`;}
  board.addEventListener('click',event=>{const cell=event.target.closest('.tile');if(cell)move(Number(cell.dataset.index));});
  document.addEventListener('keydown',event=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key)||state.phase==='finished')return;event.preventDefault();const blank=state.board.indexOf(0),row=Math.floor(blank/4),col=blank%4;const target={ArrowUp:row<3?blank+4:-1,ArrowDown:row>0?blank-4:-1,ArrowLeft:col<3?blank+1:-1,ArrowRight:col>0?blank-1:-1}[event.key];if(target>=0)move(target);});
  reset.addEventListener('click',()=>{state=Fifteen.createState(Fifteen.shuffle(Math.random));render();});state=Fifteen.createState(Fifteen.shuffle(Math.random));render();
})();
